name: CI
on:
  [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        include:
          - docker_image: ubuntu-22.04
            docker_arch: amd64
            compiler: clang
          - docker_image: ubuntu-22.04.s390x
            docker_arch: s390x
            compiler: clang
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Check platform
        run: uname -a
      - name: Launch Action
        uses:
          joholl/ci/runCI@main
        with:
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          DOCKER_ARCH: ${{ matrix.docker_arch }}
          CC: ${{ matrix.compiler }}
          BASE_REF: ${{ github.base_ref }}
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: cat $(find ../ -name test-suite.log) || true
